### ISSUE TITLE
Same lesson shows up twice

### ISSUE THREAD

**Issue by jazminmatos** [learn-co-curriculum/react-event-system#10]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/1396/pages/react-event-system?module_item_id=110096

## What should be changed?
React Events System and React Events Crash Course are the same exact readme. They are listed in the React Events section.

Suggest your change here. Let us know what section or line of the Readme needs
to be updated, and any proposed corrections. Include the line number(s) if
possible.

**Comment by ihollander** [comment]
@jazminmatos thanks for flagging this! We've removed one of the duplicated lessons in Canvas.
