### ISSUE TITLE
Same lesson as 'Events Crash Course Readme'

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/react-event-system#8]

**Comment by dstoll243** [comment]
Filed an issue on the other repo to try and get this addressed. https://github.com/learn-co-curriculum/react-events-crash-course-readme/issues/2

**Comment by maxwellbenton** [comment]
Hi @JoeQuattrone,

Thanks for reporting this. We are aware of this issue and are now tracking this and other order-related issues [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3).

We are currently updating and restructuring the materials in this section and will add this to our internal work queue. We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of the React curriculum.

I'm closing this issue but I invite you to follow the progress. We will notify
you here when it is resolved.

Thanks for contributing!
